Spgateway/Controllers/BankController.cs
using Newtonsoft.Json;
using Spgateway.Models;
using Spgateway.Models.CreditCardApi;
using Spgateway.Models.Util;
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Spgateway.Controllers
{
    public class BankController : Controller
    {
        /// <summary>
        /// 金流基本資料(可再移到Web.config或資料庫設定)
        /// </summary>
        private BankInfoModel _bankInfoModel = new BankInfoModel
        {
            MerchantID = "MS00000000",
            HashKey = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            HashIV = "xxxxxxxxxxxx",
            ReturnURL = "http://yourWebsitUrl/Bank/SpgatewayReturn",
            NotifyURL = "http://yourWebsitUrl/Bank/SpgatewayNotify",
            CustomerURL = "http://yourWebsitUrl/Bank/SpgatewayCustomer",
            AuthUrl = "https://ccore.spgateway.com/MPG/mpg_gateway",
            CloseUrl = "https://core.newebpay.com/API/CreditCard/Close"
        };

        /// <summary>
        /// 付款頁面
        /// </summary>
        /// <returns></returns>
        public ActionResult PayBill()
        {
            return View();
        }

        /// <summary>
        /// [智付通支付]金流介接
        /// </summary>
        /// <param name="ordernumber">訂單單號</param>
        /// <param name="amount">訂單金額</param>
        /// <param name="payType">請款類型</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult SpgatewayPayBill(string ordernumber, int amount, string payType)
        {
            string version = "1.5";

            // 目前時間轉換 +08:00, 防止傳入時間或Server時間時區不同造成錯誤
            DateTimeOffset taipeiStandardTimeOffset = DateTimeOffset.Now.ToOffset(new TimeSpan(8, 0, 0));

            TradeInfo tradeInfo = new TradeInfo()
            {
                // * 商店代號
                MerchantID = _bankInfoModel.MerchantID,
                // * 回傳格式
                RespondType = "String",
                // * TimeStamp
                TimeStamp = taipeiStandardTimeOffset.ToUnixTimeSeconds().ToString(),
                // * 串接程式版本
                Version = version,
                // * 商店訂單編號
                //MerchantOrderNo = $"T{DateTime.Now.ToString("yyyyMMddHHmm")}",
                MerchantOrderNo = ordernumber,
                // * 訂單金額
                Amt = amount,
                // * 商品資訊
                ItemDesc = "商品資訊(自行修改)",
                // 繳費有效期限(適用於非即時交易)
                ExpireDate = null,
                // 支付完成 返回商店網址
                ReturnURL = _bankInfoModel.ReturnURL,
                // 支付通知網址
                NotifyURL = _bankInfoModel.NotifyURL,
                // 商店取號網址
                CustomerURL = _bankInfoModel.CustomerURL,
                // 支付取消 返回商店網址
                ClientBackURL = null,
                // * 付款人電子信箱
                Email = string.Empty,
                // 付款人電子信箱 是否開放修改(1=可修改 0=不可修改)
                EmailModify = 0,
                // 商店備註
                OrderComment = null,
                // 信用卡 一次付清啟用(1=啟用、0或者未有此參數=不啟用)
                CREDIT = null,
                // WEBATM啟用(1=啟用、0或者未有此參數，即代表不開啟)
                WEBATM = null,
                // ATM 轉帳啟用(1=啟用、0或者未有此參數，即代表不開啟)
                VACC = null,
                // 超商代碼繳費啟用(1=啟用、0或者未有此參數，即代表不開啟)(當該筆訂單金額小於 30 元或超過 2 萬元時，即使此參數設定為啟用，MPG 付款頁面仍不會顯示此支付方式選項。)
                CVS = null,
                // 超商條碼繳費啟用(1=啟用、0或者未有此參數，即代表不開啟)(當該筆訂單金額小於 20 元或超過 4 萬元時，即使此參數設定為啟用，MPG 付款頁面仍不會顯示此支付方式選項。)
                BARCODE = null
            };

            if (string.Equals(payType, "CREDIT"))
            {
                tradeInfo.CREDIT = 1;
            }
            else if (string.Equals(payType, "WEBATM"))
            {
                tradeInfo.WEBATM = 1;
            }
            else if (string.Equals(payType, "VACC"))
            {
                // 設定繳費截止日期
                tradeInfo.ExpireDate = taipeiStandardTimeOffset.AddDays(1).ToString("yyyyMMdd");
                tradeInfo.VACC = 1;
            }
            else if (string.Equals(payType, "CVS"))
            {
                // 設定繳費截止日期
                tradeInfo.ExpireDate = taipeiStandardTimeOffset.AddDays(1).ToString("yyyyMMdd");
                tradeInfo.CVS = 1;
            }
            else if (string.Equals(payType, "BARCODE"))
            {
                // 設定繳費截止日期
                tradeInfo.ExpireDate = taipeiStandardTimeOffset.AddDays(1).ToString("yyyyMMdd");
                tradeInfo.BARCODE = 1;
            }

            Atom<string> result = new Atom<string>()
            {
                IsSuccess = true
            };

            var inputModel = new SpgatewayInputModel
            {
                MerchantID = _bankInfoModel.MerchantID,
                Version = version
            };

            // 將model 轉換為List<KeyValuePair<string, string>>, null值不轉
            List<KeyValuePair<string, string>> tradeData = LambdaUtil.ModelToKeyValuePairList<TradeInfo>(tradeInfo);
            // 將List<KeyValuePair<string, string>> 轉換為 key1=Value1&key2=Value2&key3=Value3...
            var tradeQueryPara = string.Join("&", tradeData.Select(x => $"{x.Key}={x.Value}"));
            // AES 加密
            inputModel.TradeInfo = CryptoUtil.EncryptAESHex(tradeQueryPara, _bankInfoModel.HashKey, _bankInfoModel.HashIV);
            // SHA256 加密
            inputModel.TradeSha = CryptoUtil.EncryptSHA256($"HashKey={_bankInfoModel.HashKey}&{inputModel.TradeInfo}&HashIV={_bankInfoModel.HashIV}");

            // 將model 轉換為List<KeyValuePair<string, string>>, null值不轉
            List<KeyValuePair<string, string>> postData = LambdaUtil.ModelToKeyValuePairList<SpgatewayInputModel>(inputModel);

            Response.Clear();

            StringBuilder s = new StringBuilder();
            s.Append("<html>");
            s.AppendFormat("<body onload='document.forms[\"form\"].submit()'>");
            s.AppendFormat("<form name='form' action='{0}' method='post'>", _bankInfoModel.AuthUrl);
            foreach (KeyValuePair<string, string> item in postData)
            {
                s.AppendFormat("<input type='hidden' name='{0}' value='{1}' />", item.Key, item.Value);
            }

            s.Append("</form></body></html>");
            Response.Write(s.ToString());
            Response.End();

            return Content(string.Empty);

        }

        /// <summary>
        /// [智付通]金流介接(結果: 支付完成 返回商店網址)
        /// </summary>
        [HttpPost]
        public ActionResult SpgatewayReturn()
        {
            Request.LogFormData("SpgatewayReturn(支付完成)");

            // Status 回傳狀態 
            // MerchantID 回傳訊息
            // TradeInfo 交易資料AES 加密
            // TradeSha 交易資料SHA256 加密
            // Version 串接程式版本
            NameValueCollection collection = Request.Form;

            if (collection["MerchantID"] != null && string.Equals(collection["MerchantID"], _bankInfoModel.MerchantID) &&
                collection["TradeInfo"] != null && string.Equals(collection["TradeSha"], CryptoUtil.EncryptSHA256($"HashKey={_bankInfoModel.HashKey}&{collection["TradeInfo"]}&HashIV={_bankInfoModel.HashIV}")))
            {
                var decryptTradeInfo = CryptoUtil.DecryptAESHex(collection["TradeInfo"], _bankInfoModel.HashKey, _bankInfoModel.HashIV);

                // 取得回傳參數(ex:key1=value1&key2=value2),儲存為NameValueCollection
                NameValueCollection decryptTradeCollection = HttpUtility.ParseQueryString(decryptTradeInfo);
                SpgatewayOutputDataModel convertModel = LambdaUtil.DictionaryToObject<SpgatewayOutputDataModel>(decryptTradeCollection.AllKeys.ToDictionary(k => k, k => decryptTradeCollection[k]));

                LogUtil.WriteLog(JsonConvert.SerializeObject(convertModel));

                // TODO 將回傳訊息寫入資料庫

                return Content(JsonConvert.SerializeObject(convertModel));
            }
            else
            {
                LogUtil.WriteLog("MerchantID/TradeSha驗證錯誤");
            }

            return Content(string.Empty);
        }

        /// <summary>
        /// [智付通]金流介接(結果: 支付通知網址)
        /// </summary>
        [HttpPost]
        public ActionResult SpgatewayNotify()
        {
            // 取法同SpgatewayResult

            Request.LogFormData("SpgatewayNotify(支付通知)");
            return Content(string.Empty);
        }

        /// <summary>
        /// [智付通]金流介接(結果: 資料回傳)
        /// </summary>
        [HttpPost]
        public ActionResult SpgatewayCustomer()
        {
            Request.LogFormData("SpgatewayCustomer(資料回傳)");

            // Status 回傳狀態 
            // MerchantID 回傳訊息
            // TradeInfo 交易資料AES 加密
            // TradeSha 交易資料SHA256 加密
            // Version 串接程式版本
            NameValueCollection collection = Request.Form;

            if (collection["MerchantID"] != null && string.Equals(collection["MerchantID"], _bankInfoModel.MerchantID))
            {
                var decryptTradeInfo = CryptoUtil.DecryptAESHex(collection["TradeInfo"], _bankInfoModel.HashKey, _bankInfoModel.HashIV);

                // 取得回傳參數(ex:key1=value1&key2=value2),儲存為NameValueCollection
                NameValueCollection decryptTradeCollection = HttpUtility.ParseQueryString(decryptTradeInfo);
                SpgatewayTakeNumberDataModel convertModel = LambdaUtil.DictionaryToObject<SpgatewayTakeNumberDataModel>(decryptTradeCollection.AllKeys.ToDictionary(k => k, k => decryptTradeCollection[k]));

                LogUtil.WriteLog(JsonConvert.SerializeObject(convertModel));

                // TODO 將回傳訊息寫入資料庫

                return Content(JsonConvert.SerializeObject(convertModel));
            }
            else
            {
                LogUtil.WriteLog("MerchantID錯誤");
            }

            return Content(string.Empty);
        }

        /// <summary>
        /// 執行HttpClient Post
        /// </summary>

Spgateway/Views/Bank/PayBill.cshtml
@{
    ViewBag.Title = "PayBill";
}

@section scripts
{
    <script>
        angular.module("MainApp", ["ngMaterial", "ngMessages"])
            .controller("MainCtrl", ["$http", function ($http) {
                common.log("angular");
            }]);
    </script>

}


<div ng-module="MainApp" ng-controller="MainCtrl as ctrl" style="padding-top: 50px">
    <br />
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapse">測試網頁</a>
            </h4>
        </div>
        <div id="collapse" class="panel-collapse collapse in">
            <div class="panel-body">

                <form class="form-horizontal" role="form" action="@Url.Action("SpgatewayPayBill", "Bank")" method="POST">

                    <div class="row">
                        <div class="col-md-12">
                            <md-input-container class="md-block">
                                <label>訂單編號</label>
                                <input type="text"
                                       class="form-control"
                                       required="required"
                                       name="orderNumber"
                                       maxlength="20">
                            </md-input-container>
                        </div>

                        <div class="col-md-12">
                            <md-input-container class="md-block">
                                <label>訂單金額</label>
                                <input type="text"
                                       class="form-control"
                                       required="required"
                                       name="amount">
                            </md-input-container>
                        </div>
                        <div class="col-md-12">
                            <md-input-container>
                                <label>請款類型</label>
                                <md-select name="payType" ng-model="payType">
                                    <md-option value="CREDIT">信用卡</md-option>
                                    <md-option value="WEBATM">WEBATM</md-option>
                                    <md-option value="VACC">ATM 轉帳</md-option>
                                    <md-option value="CVS">超商代碼繳費</md-option>
                                    <md-option value="BARCODE">超商條碼繳費</md-option>
                                </md-select>
                            </md-input-container>
                        </div>
                        <div class="col-md-12">
                            <button type="submit" class="btn btn-success">
                                確定
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

Spgateway/Views/Bank/RefundTest.cshtml
@{
    ViewBag.Title = "Test";
}

@section scripts
{

    <style>
        /*解決 md-select選取時,scrollbar會移到top問題*/
        body {
            height: auto;
        }

        /*body[style] {
            position: static !important;
            top: inherit !important;
            width: inherit !important;
        }*/
    </style>


    <script>
        var bag = {
            SpgatewayCloseUrl: '@Url.Content("~/Bank/SpgatewayClose")'
        };

        angular.module("SpgatewayApp", ["ngMaterial", "ngMessages"])
            .controller("SpgatewayCtrl", ["$http", function ($http) {
                common.log("angular");

                var ctrl = this;

                var postUrl = function (url, model) {
                    $http.post(url, model).then(
                        function (response) {

                            common.log(response);

                            var ret = response.data;
                            if (!ret) {
                                common.Alert("發生錯誤");
                            }
                            else if (ret.IsSuccess) {
                                common.Alert({
                                    title: "Success",
                                    message: ret.Message
                                });
                            }
                            else {
                                common.Alert({
                                    title: "失敗",
                                    message: ret.Message
                                });
                            }

                        },
                        function (errResponse) {
                            common.log(errResponse);
                        });
                };

                ctrl.CloseData = {

                };

                // (取消)請退款
                ctrl.close = function () {
                    common.log("ctrl.close");
                    postUrl(bag.SpgatewayCloseUrl, ctrl.CloseData);
                };

            }]);

    </script>
}


<div style="padding-top: 50px">

    <br />
    <h2>智付通</h2>
    <div class="panel-group" id="accordionSpgateway" ng-module="SpgatewayApp" ng-controller="SpgatewayCtrl as ctrl">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordionSpgateway" href="#collapseSpgateway2">(取消)請退款</a>
                </h4>
            </div>
            <div id="collapseSpgateway2" class="panel-collapse collapse in">
                <div class="panel-body">
                    <form class="form-horizontal" role="form" ng-submit="ctrl.close()">

                        <div class="row">

                            <div class="col-md-12">
                                <md-input-container class="md-block">
                                    <label>商店訂單編號</label>
                                    <input type="text"
                                           class="form-control"
                                           required="required"
                                           ng-model="ctrl.CloseData.MerchantOrderNo"
                                           maxlength="20">
                                </md-input-container>
                            </div>

                            <div class="col-md-12">
                                <md-input-container class="md-block">
                                    <label>訂單金額</label>
                                    <input type="text"
                                           class="form-control"
                                           required="required"
                                           ng-model="ctrl.CloseData.Amt">
                                </md-input-container>
                            </div>

                            <div class="col-md-12">
                                <md-input-container>
                                    <label>類型</label>
                                    <md-select ng-model="ctrl.CloseData.ExeType">
                                        <md-option value="DepositReversal">取消請款</md-option>
                                        <md-option value="Refund">退款</md-option>
                                        <md-option value="RefundReversal">取消退款</md-option>
                                    </md-select>
                                </md-input-container>
                            </div>

                            <div class="col-md-12">
                                <button type="submit" class="btn btn-success">
                                    確定
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@Html.Partial("_Alert")